### ISSUE TITLE
font.dirty is always set upon opening

### ISSUE THREAD

**Issue by adrientetar** [trufont/defcon#2]
This happens since the migration to ufo3.

~~~
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\__main__.py", line 23, in <module>
    window = MainWindow(font)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 630, in __init__
    self.font = font
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 934, in _set_font
    self._font.lib["public.glyphOrder"])
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 950, in _set_sortDescriptor
    glyphs.append(self._font[glyphName])
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 208, in __getitem__
    return self._glyphSet[name]
  File "C:\Python34\lib\site-packages\defcon\objects\layer.py", line 250, in __getitem__
    self.loadGlyph(name)
  File "C:\Python34\lib\site-packages\defcon\objects\layer.py", line 169, in loadGlyph
    glyph.name = name
  File "C:\Python34\lib\site-packages\defcon\objects\glyph.py", line 194, in _set_name
    self.dirty = True
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 60, in _set_dirty
    print(traceback.format_exc())
~~~

It seems a bug in defcon: everytime a glyph is loaded from a layer object, it sets attributes when instanciating the object which create a self.dirty notification.

cc @graphicore

**Comment by graphicore** [comment]
This is interesting, I remember I once complained about the name attribute of a glyph in ufo being bad normalization and redundant. IMHO the single source of truth for glyph names should be the layers contents.plist.

There is even a bit about it in **The UFO Design Philosophy** http://unifiedfontobject.org/index.html:
> 3. Data duplication should be avoided unless absolutely necessary.

**Comment by adrientetar** [comment]
I don't see how it relates to this issue: the problem we have here is that when you call loadGlyph() it instanciates a glyph object and when setting this object's attributes glyph.dirty gets set.

There is a call to glyph.disableNotifications() at the beginning of the function but this only prevents dirty state from being notified, not set. So currently when we open a font all glyphs are dirty.

A naive fix would be to set glyph.dirty = False at the end of the function.

**Comment by graphicore** [comment]
> I don't see how it relates to this issue

The root of it is a bad spec, if you ask me.

> A naive fix would be to set glyph.dirty = False at the end of the function.

You can even do this in a child class. To take it upstream, we should involve Tal.

Why does this not prevent the execution of the name setter:

https://github.com/trufont/defcon/blob/python3-ufo3/Lib/defcon/objects/glyph.py#L190
```py
 if oldName != value:
```

It should prevent the issue from happening unless the name is changed indeed.

**Comment by adrientetar** [comment]
Why should this condition evaluate to False? oldName should be None when creating a new glyph object and value is the name of the glyph that loadGlyph() sets.

**Comment by adrientetar** [comment]
Wait, there is glyph.dirty = False. It must be causes by something else.

**Comment by graphicore** [comment]
> everytime a glyph is loaded from a layer object

I thought you where talking about loading a glyph, not creating a new one.

**Comment by adrientetar** [comment]
Okay, actually the root cause seems to be that when loading the layers when the font object is populated the notifications aren't disabled.

```
  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\__main__.py", line 10, in <module>
    font = TFont(os.path.abspath(sys.argv[1]))
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 15, in __init__
    super(TFont, self).__init__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 140, in __init__
    layer = self._layers.newLayer(layerName, glyphSet=glyphSet)
  File "C:\Python34\lib\site-packages\defcon\objects\layerSet.py", line 196, in newLayer
    self.dirty = True
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 874, in _objectDirtyStateChange
    self.dirty = True
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 20, in _set_dirty
    traceback.print_stack()

font: True!


  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\__main__.py", line 10, in <module>
    font = TFont(os.path.abspath(sys.argv[1]))
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 15, in __init__
    super(TFont, self).__init__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 141, in __init__
    layer.dirty = False
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "C:\Python34\lib\site-packages\defcon\objects\layerSet.py", line 339, in _layerDirtyStateChange
    self.dirty = True
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 874, in _objectDirtyStateChange
    self.dirty = True
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 20, in _set_dirty
    traceback.print_stack()

font: True!


  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\__main__.py", line 10, in <module>
    font = TFont(os.path.abspath(sys.argv[1]))
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 15, in __init__
    super(TFont, self).__init__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 144, in __init__
    self._layers.defaultLayer = self._layers[defaultLayerName]
  File "C:\Python34\lib\site-packages\defcon\objects\layerSet.py", line 115, in _set_defaultLayer
    self.dirty = True
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "C:\Python34\lib\site-packages\defcon\tools\notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "C:\Python34\lib\site-packages\defcon\objects\font.py", line 874, in _objectDirtyStateChange
    self.dirty = True
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\objects\defcon.py", line 20, in _set_dirty
    traceback.print_stack()

font: True!
```

**Comment by adrientetar** [comment]
typesupply/defcon#28
